# Generated by Django 4.2.4 on 2023-09-03 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=200)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200)),
                ('specialize', models.TextField()),
                ('doctor_image', models.ImageField(upload_to='')),
                ('deptname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospitalapp.department')),
            ],
        ),
    ]
