# Generated by Django 4.2.4 on 2023-09-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0004_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
    ]
