# Generated by Django 4.2.4 on 2023-09-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0007_delete_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
