# Generated by Django 4.2.4 on 2023-09-04 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0002_rename_doctor_image_doctors_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('ph_number', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('doc_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospitalapp.doctors')),
            ],
        ),
    ]
