# Generated by Django 4.2.4 on 2023-09-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0009_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='doctor_name',
        ),
    ]
