# Generated by Django 4.2.4 on 2023-09-07 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0010_remove_booking_doctor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('ph_number', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospitalapp.doctors')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
